### ISSUE TITLE
Support for UICollectionView

### ISSUE THREAD

**Issue by richardtop** [dmytro-anokhin/TableViewDataSource#1]
Hi, thanks for a nice demo project.

I've been using a similar concept for `UICollectionView`, it worked fine, except a couple of challenges related to proxying in Swift.

Hence, I have a couple of questions:
1. Why does the _ObjCTableViewProxy_ inherits of _NSObject_ and not _NSProxy_? Are there some reasons behind this decision?
2. Are you planning to add support for the _UICollectionView_? The original Apple sample code was based on the _UICollectionView_ and allowed for greater flexibility.
3. Are you going to release this framework to CocoaPods?

Overall, I find this pattern very helpful when the API doesn't map 1-to-1 to the app's screens. For example, when the app needs to display content from multiple endpoints on a single screen.

Also, it allows quickly mix different sections and iterate on the app design.

Best regards,
Richard

**Comment by dmytro-anokhin** [comment]
Hi Richard,

thanks for expressed interest.

Re. your questions.

Main reason of using `NSObject` is following Apple sample code. However, I find `NSObject` to be more suitable and convenient here. `ObjCTableViewProxy` is not a pure proxy. It has two intentions. First is to "hook" `UITableView` methods that accept section or indexPath as an argument. Second is to provide subclassing for `TableViewProxy`, that serves as a bridge between Swift and Objective-C. This goes beyond `NSProxy` intention to act as stand-ins for other object. Potentially there may be more intentions, like synchronizing `UITableView` updates and registering reusable views. But I'm still exploring this ideas.

I really want to add support for the `UICollectionView`. Though, I can't promise this to happen soon. TableViewDataSource is my pet project with all "find the spare time" challenges. One alternative I can give if you have complex UI, but without multiple repeating elements, - consider using composition of `UIViewController`. It is much simpler when you don't have to deal with `IndexPath`.

CocoaPods (and other package managers) - yes, this will be the next step, after I consider framework solid enough. Decent unit test coverage is the main factor here.

Thank you,
Dmytro

**Comment by richardtop** [comment]
Thanks for your feedback, Dmytro.

Replying to your comments:
1. I've tested your approach with _UICollectionView_ and _NSProxy_, both were successful. I went with _NSObject_ though.
2. _UIViewController_ composition is a good technique actually. However, it doesn't apply well for mixing content with infinitely-scrollable lists. In this case I'll need to handle cell reuse in Scroll/Collection views. Although, reloading becomes dead simple, as the complexity is contained inside individual controllers.

My 1st attempt in replicating this architecture in Swift was partially successful, I've created an _CollectionViewProtocol_, forcing all the datasources to mention it instead of the _UICollectionView_. The proxy was an instance conforming to this protocol (or the _UICollectionView_ itself).

My last question would be about architecture - in my app I managed to use a shared controller and achieve completely different behaviors by simply setting a different DataSource. What's your views on the controller's role in this architecture?

Overall, I'm looking forward to seeing your progress in this project. I might open-source my own implementation with UICollectionView eventually.

**Comment by dmytro-anokhin** [comment]
Hi Richard,

`UIViewController` becomes more of a view controller, rather than view-model controller. It keeps responsibilities to manage the table view and coordinating with other view controllers, objects. Maybe handling user interactions or certain actions delegated by data sources.

Because a data source is now managing content, a view controller can be generic. We can inject a data source. This creates an opportunity to replace imperative screen construction process with declarative approach. Something I commonly see with the composite pattern.


Thank you,
Dmytro

**Comment by richardtop** [comment]
Thanks for the feedback. Looking forward to seeing your progress with this concept.
Meanwhile, while I'm working on the same idea, but for the `UICollectionView`, the only challenge I've encountered, is that I try to put too much to the DataSource itself.

I'll keep this issue open as I guess, the `UICollectionView` support can be considered a nice-to-have feature for this project.
